/* ============================================================
   SOMOS BACANES — BASE DE DATOS DE GENIALIDADES
   ============================================================
   Este es el ÚNICO archivo que necesitas editar para sumar
   nuevas genialidades al mapa. Cada objeto = una carta.

   CÓMO AGREGAR UNA GENIALIDAD NUEVA:
   1. Copia un bloque { ... } completo, incluyendo la coma final.
   2. Pégalo dentro de [ ] (puede ir en cualquier orden).
   3. Cambia los valores. Campos obligatorios explicados abajo.
   4. Guarda. Listo: aparece sola en el mapa y en el mazo.

   CAMPOS:
   - reg    : código de la región donde ocurre (ver tabla abajo).
   - cat    : categoría visual. Define el COLOR de la carta.
              Opciones válidas: 'recursos' | 'cielo' | 'natura' | 'gente'
   - catEs/catEn : etiqueta de categoría mostrada (ES / EN).
   - rankEs/rankEn : el "sello" arriba (ej: '#1 del mundo').
   - big    : la cifra GRANDE protagonista (ej: '23%', '#1', '🐧').
   - labelEs/labelEn : la frase principal bajo la cifra.
   - vsEs/vsEn : el recuadro "Chile vs el mundo". Acepta <b>negrita</b>.
   - src    : la fuente del dato (se muestra abajo, da credibilidad).
   - slug   : (OPCIONAL) conecta esta carta con un artículo del blog.
              Pon el mismo 'slug' del artículo en articulos.js y aparecerá
              un botón "Leer más" que lleva al artículo.
              Ej: slug:'momias-chinchorro'. Si no hay artículo, omítelo.

   TABLA DE CÓDIGOS DE REGIÓN (norte → sur):
     15 = Arica y Parinacota      8  = Biobío
     1  = Tarapacá                9  = La Araucanía
     2  = Antofagasta             14 = Los Ríos
     3  = Atacama                 10 = Los Lagos
     4  = Coquimbo                11 = Aysén
     5  = Valparaíso              12 = Magallanes
     13 = Metropolitana
     6  = O'Higgins
     7  = Maule
     16 = Ñuble
   ============================================================ */

const DATA = [

  /* ===================== ZONA NORTE ===================== */

  /* ---------- ARICA Y PARINACOTA (15) ---------- */
  {reg:15,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Las más antiguas',rankEn:'The oldest',big:'7.000',
   labelEs:'años tienen las momias Chinchorro, las más antiguas del mundo',labelEn:'years old: the Chinchorro mummies, the oldest in the world',
   vsEs:'Más antiguas que las egipcias por <b>dos mil años</b>. Patrimonio de la Humanidad UNESCO.',
   vsEn:'Older than the Egyptian ones by <b>two thousand years</b>. A UNESCO World Heritage treasure.',
   src:'UNESCO', slug:'momias-chinchorro'},
  {reg:15,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Eterna primavera',rankEn:'Eternal spring',big:'18°C',
   labelEs:'Arica: temperatura casi perfecta todo el año, "ciudad de la eterna primavera"',labelEn:'Arica: near-perfect temperature year-round, the "city of eternal spring"',
   vsEs:'Una de las ciudades <b>más secas del planeta</b> (0,5 mm de lluvia al año) y de clima más estable.',
   vsEn:'One of the <b>driest cities on Earth</b> (0.5 mm of rain a year) with one of the most stable climates.',
   src:'Köppen / AricaMía'},
  {reg:15,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Lago altísimo',rankEn:'Sky-high lake',big:'4.500m',
   labelEs:'el lago Chungará, uno de los lagos navegables más altos del mundo',labelEn:'Lake Chungará, one of the highest lakes in the world',
   vsEs:'A los pies del volcán Parinacota, con flamencos y vicuñas. <b>Un paisaje de otro planeta.</b>',
   vsEn:'At the foot of the Parinacota volcano, with flamingos and vicuñas. <b>A landscape from another planet.</b>',
   src:'CONAF / Parque Nacional Lauca'},
  {reg:15,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Surf de clase mundial',rankEn:'World-class surf',big:'🏄',
   labelEs:'las playas del norte: olas de nivel mundial todo el año',labelEn:'the northern beaches: world-class waves all year long',
   vsEs:'Aguas templadas y olas consistentes hacen del norte <b>un paraíso para surfistas</b> de todo el mundo.',
   vsEn:'Warm water and consistent waves make the north <b>a paradise for surfers</b> from around the world.',
   src:'Sernatur'},
  {reg:15,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cultura viva',rankEn:'Living culture',big:'Aymara',
   labelEs:'la cultura aymara sigue viva en el altiplano, con su lengua y tradiciones',labelEn:'the Aymara culture lives on in the highlands, with its language and traditions',
   vsEs:'Pueblos como Putre mantienen <b>milenios de tradición andina</b> a más de 3.500 metros de altura.',
   vsEn:'Villages like Putre keep <b>millennia of Andean tradition</b> alive above 3,500 metres.',
   src:'Memoria Chilena'},

  /* ---------- TARAPACÁ (1) ---------- */
  {reg:1,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Récord solar',rankEn:'Solar record',big:'#1',
   labelEs:'la radiación solar más alta del planeta se mide en el norte de Chile',labelEn:'the highest solar radiation on Earth is measured in northern Chile',
   vsEs:'El desierto recibe <b>tanto sol que es uno de los mejores lugares del mundo</b> para energía solar.',
   vsEn:'The desert gets <b>so much sun it is one of the best places on Earth</b> for solar power.',
   src:'Journal of Geophysical Research'},
  {reg:1,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Patrimonio',rankEn:'Heritage',big:'UNESCO',
   labelEs:'Humberstone y Santa Laura: pueblos del salitre, Patrimonio de la Humanidad',labelEn:'Humberstone & Santa Laura: saltpeter towns, World Heritage Sites',
   vsEs:'Ciudades fantasma del auge del salitre que <b>movió la economía mundial</b> a inicios del siglo XX.',
   vsEn:'Ghost towns from the saltpeter boom that <b>powered the world economy</b> in the early 1900s.',
   src:'UNESCO, 2005'},
  {reg:1,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Arte milenario',rankEn:'Ancient art',big:'450+',
   labelEs:'geoglifos de Pintados: figuras gigantes grabadas hace siglos en el desierto',labelEn:'the Pintados geoglyphs: giant figures carved into the desert centuries ago',
   vsEs:'Más de 450 figuras prehispánicas talladas en los cerros. <b>Arte a escala de paisaje.</b>',
   vsEn:'Over 450 pre-Hispanic figures carved into the hills. <b>Art on a landscape scale.</b>',
   src:'Sernatur'},
  {reg:1,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Playas top',rankEn:'Top beaches',big:'🏖️',
   labelEs:'Iquique: playas urbanas entre las mejores del país, con el desierto al lado',labelEn:'Iquique: urban beaches among the best in the country, with the desert next door',
   vsEs:'Donde la duna gigante del Cerro Dragón <b>se encuentra con el mar</b>: parapente y playa el mismo día.',
   vsEn:'Where the giant Cerro Dragón dune <b>meets the sea</b>: paragliding and beach on the same day.',
   src:'Sernatur'},
  {reg:1,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Oasis del desierto',rankEn:'Desert oasis',big:'🍋',
   labelEs:'Pica: un oasis con frutas únicas en medio del desierto más seco',labelEn:'Pica: an oasis with unique fruit in the middle of the driest desert',
   vsEs:'El limón de Pica es <b>famoso en todo Chile</b>: vida que florece donde no debería haber agua.',
   vsEn:'The Pica lemon is <b>famous across Chile</b>: life flourishing where there should be no water.',
   src:'Sernatur'},

  /* ---------- ANTOFAGASTA (2) ---------- */
  {reg:2,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'#1 del mundo',rankEn:'#1 in the world',big:'23%',
   labelEs:'del cobre del planeta sale de Chile',labelEn:"of the planet's copper comes from Chile",
   vsEs:'Chile produce <b>tanto cobre como los dos países siguientes juntos</b>: 5,3 millones de toneladas al año.',
   vsEn:'Chile produces <b>as much copper as the next two countries combined</b>: 5.3 million tonnes a year.',
   src:'USGS / Investing News, 2025'},
  {reg:2,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Top mundial',rankEn:'World top',big:'40%',
   labelEs:'del litio del mundo está bajo el desierto de Atacama',labelEn:"of the world's lithium lies under the Atacama Desert",
   vsEs:'El litio mueve las baterías de los autos eléctricos del mundo. <b>Buena parte empieza acá.</b>',
   vsEn:"Lithium powers the world's EV batteries. <b>A big chunk of it starts right here.</b>",
   src:'Earthworks / USGS'},
  {reg:2,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'El más avanzado',rankEn:'Most advanced',big:'VLT',
   labelEs:'Cerro Paranal: el observatorio de luz visible más avanzado del mundo',labelEn:'Cerro Paranal: the most advanced visible-light observatory in the world',
   vsEs:'Sus telescopios ven objetos <b>4.000 millones de veces más débiles</b> que lo que percibe el ojo humano.',
   vsEn:'Its telescopes see objects <b>4 billion times fainter</b> than the human eye can detect.',
   src:'ESO', slug:'desierto-atacama-cielos'},
  {reg:2,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Paisaje marciano',rankEn:'Martian landscape',big:'🌗',
   labelEs:'el Valle de la Luna en San Pedro: tan parecido a otro planeta que la NASA lo usa',labelEn:'the Valley of the Moon in San Pedro: so otherworldly that NASA uses it',
   vsEs:'Dunas, sal y formaciones que parecen <b>la superficie de Marte</b>. Atardeceres de otro mundo.',
   vsEn:'Dunes, salt and formations that look like <b>the surface of Mars</b>. Otherworldly sunsets.',
   src:'NASA / Sernatur'},
  {reg:2,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Géiseres altísimos',rankEn:'Sky-high geysers',big:'4.300m',
   labelEs:'el Tatio: uno de los campos de géiseres más altos del mundo',labelEn:'El Tatio: one of the highest geyser fields in the world',
   vsEs:'Decenas de columnas de vapor al amanecer a más de 4.000 metros. <b>Espectáculo natural único.</b>',
   vsEn:'Dozens of steam columns at dawn above 4,000 metres. <b>A unique natural spectacle.</b>',
   src:'CONAF'},

  /* ---------- ATACAMA (3) ---------- */
  {reg:3,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'El más seco',rankEn:'The driest',big:'#1',
   labelEs:'desierto más seco del mundo: Atacama',labelEn:'driest desert in the world: Atacama',
   vsEs:'Hay zonas donde <b>no se registra lluvia por décadas</b>. La NASA lo usa para probar tecnología que irá a Marte.',
   vsEn:'There are spots where <b>no rain falls for decades</b>. NASA tests Mars-bound tech here.',
   src:'History / NASA'},
  {reg:3,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Florece',rankEn:'It blooms',big:'🌸',
   labelEs:'el desierto más seco florece de colores tras la lluvia',labelEn:'the driest desert blooms in color after the rain',
   vsEs:'El "desierto florido" es un fenómeno <b>casi único en el planeta</b>: la vida estalla donde no debería existir.',
   vsEn:'The "flowering desert" is a phenomenon <b>almost unique on Earth</b>: life explodes where it should not exist.',
   src:'Atlas of Wonders'},
  {reg:3,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Resiliencia total',rankEn:'Total resilience',big:'33',
   labelEs:'los 33 mineros: rescatados tras 69 días bajo tierra, hazaña vista por el mundo',labelEn:'the 33 miners: rescued after 69 days underground, a feat watched by the world',
   vsEs:'El rescate de la mina San José en 2010 fue <b>seguido en vivo por mil millones de personas</b>.',
   vsEn:'The 2010 San José mine rescue was <b>watched live by a billion people</b> around the world.',
   src:'BBC / 2010'},
  {reg:3,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Playas vírgenes',rankEn:'Pristine beaches',big:'🏝️',
   labelEs:'Bahía Inglesa: aguas turquesas en pleno borde del desierto',labelEn:'Bahía Inglesa: turquoise waters right at the desert\'s edge',
   vsEs:'Agua cristalina color Caribe <b>junto al desierto más árido del mundo</b>. Un contraste imposible.',
   vsEn:'Crystal Caribbean-blue water <b>next to the driest desert on Earth</b>. An impossible contrast.',
   src:'Sernatur'},
  {reg:3,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Camino inca',rankEn:'Inca trail',big:'Qhapaq Ñan',
   labelEs:'el Qhapaq Ñan: la red vial inca de 30.000 km, Patrimonio de la Humanidad',labelEn:'the Qhapaq Ñan: the 30,000 km Inca road network, a World Heritage Site',
   vsEs:'Una autopista andina prehispánica que cruzaba <b>seis países actuales</b>. Ingeniería milenaria.',
   vsEn:'A pre-Hispanic Andean highway crossing <b>six modern countries</b>. Millennia-old engineering.',
   src:'UNESCO'},

  /* ---------- COQUIMBO (4) ---------- */
  {reg:4,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Cielos Starlight',rankEn:'Starlight skies',big:'⭐',
   labelEs:'el Valle del Elqui: uno de los mejores cielos del mundo para mirar estrellas',labelEn:'the Elqui Valley: one of the best skies on Earth for stargazing',
   vsEs:'Tan limpios que tiene <b>observatorios turísticos</b> donde cualquiera ve galaxias a simple vista.',
   vsEn:'So clear it has <b>tourist observatories</b> where anyone can see galaxies with the naked eye.',
   src:'Fundación Starlight'},
  {reg:4,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cuna de un Nobel',rankEn:'Birthplace of a Nobel',big:'🏅',
   labelEs:'Vicuña: cuna de Gabriela Mistral, primera Nobel latinoamericana',labelEn:'Vicuña: birthplace of Gabriela Mistral, first Latin American Nobel laureate',
   vsEs:'La poeta del Valle del Elqui fue <b>la primera persona de América Latina en ganar el Nobel</b> (1945).',
   vsEn:'The poet from the Elqui Valley was <b>the first Latin American ever to win the Nobel</b> (1945).',
   src:'The Nobel Prize'},
  {reg:4,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Espíritu nacional',rankEn:'National spirit',big:'🍇',
   labelEs:'el pisco: el destilado bandera de Chile nace en estos valles',labelEn:'pisco: Chile\'s flagship spirit is born in these valleys',
   vsEs:'Uvas que con el sol del valle se convierten en <b>el destilado más chileno que existe</b>.',
   vsEn:'Grapes that, under the valley sun, become <b>the most Chilean spirit there is</b>.',
   src:'Denominación de Origen Pisco'},
  {reg:4,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Pingüinos',rankEn:'Penguins',big:'🐧',
   labelEs:'la Reserva Pingüino de Humboldt: delfines, ballenas y pingüinos juntos',labelEn:'the Humboldt Penguin Reserve: dolphins, whales and penguins together',
   vsEs:'En Isla Damas conviven <b>pingüinos, delfines nariz de botella y hasta ballenas</b>. Biodiversidad pura.',
   vsEn:'Damas Island is home to <b>penguins, bottlenose dolphins and even whales</b>. Pure biodiversity.',
   src:'CONAF'},
  {reg:4,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Valle mágico',rankEn:'Magical valley',big:'✨',
   labelEs:'el Valle del Elqui: considerado un centro de energía a nivel mundial',labelEn:'the Elqui Valley: regarded worldwide as a center of energy',
   vsEs:'Místico, luminoso y lleno de cielo. Un destino que <b>atrae viajeros de todo el mundo</b>.',
   vsEn:'Mystical, luminous and full of sky. A destination that <b>draws travelers from all over the world</b>.',
   src:'Sernatur'},

  /* ===================== ZONA CENTRO ===================== */

  /* ---------- VALPARAÍSO (5) ---------- */
  {reg:5,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Patrimonio',rankEn:'Heritage',big:'UNESCO',
   labelEs:'Valparaíso: puerto bohemio Patrimonio de la Humanidad',labelEn:'Valparaíso: bohemian port and World Heritage Site',
   vsEs:'Cerros, ascensores centenarios y uno de los <b>murales a cielo abierto</b> más coloridos de Sudamérica.',
   vsEn:'Hills, century-old funiculars and one of the most colorful <b>open-air murals</b> in South America.',
   src:'UNESCO'},
  {reg:5,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'El más aislado',rankEn:'Most remote',big:'🗿',
   labelEs:'Rapa Nui: el territorio habitado más aislado del mundo, con los moái',labelEn:'Rapa Nui: the most remote inhabited place on Earth, home of the moái',
   vsEs:'A 3.500 km de la costa. Casi <b>mil estatuas gigantes</b> que siguen siendo un misterio mundial.',
   vsEn:'3,500 km from the coast. Nearly <b>a thousand giant statues</b> that remain a global mystery.',
   src:'UNESCO / Chile Travel'},
  {reg:5,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'El más grande',rankEn:'The biggest',big:'🎤',
   labelEs:'el Festival de Viña: uno de los eventos musicales más importantes de Latinoamérica',labelEn:'the Viña Festival: one of the biggest music events in Latin America',
   vsEs:'Desde 1960 reúne a las grandes estrellas del mundo frente a la <b>exigente Quinta Vergara</b>.',
   vsEn:'Since 1960 it has gathered the world\'s biggest stars before the <b>demanding Quinta Vergara crowd</b>.',
   src:'Memoria Chilena'},
  {reg:5,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cuna financiera',rankEn:'Financial cradle',big:'1ª',
   labelEs:'Valparaíso tuvo la primera bolsa de comercio y el diario más antiguo de Chile',labelEn:'Valparaíso had Chile\'s first stock exchange and oldest newspaper',
   vsEs:'Fue el <b>gran puerto del Pacífico sur</b> antes del Canal de Panamá: el motor económico del país.',
   vsEn:'It was the <b>great port of the South Pacific</b> before the Panama Canal: the country\'s economic engine.',
   src:'Memoria Chilena'},
  {reg:5,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Casa de poeta',rankEn:'Poet\'s home',big:'🖋️',
   labelEs:'Isla Negra: la casa de Pablo Neruda frente al mar, hoy museo mundial',labelEn:'Isla Negra: Pablo Neruda\'s seaside house, now a world-famous museum',
   vsEs:'Donde el <b>Nobel de Literatura</b> escribió mirando el Pacífico. Peregrinaje de lectores de todo el mundo.',
   vsEn:'Where the <b>Nobel laureate</b> wrote facing the Pacific. A pilgrimage for readers worldwide.',
   src:'Fundación Neruda'},

  /* ---------- METROPOLITANA (13) ---------- */
  {reg:13,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'2 Nobel',rankEn:'2 Nobel laureates',big:'2',
   labelEs:'Premios Nobel de Literatura para un país de 20 millones',labelEn:'Nobel Prizes in Literature for a country of 20 million',
   vsEs:'Gabriela Mistral y Pablo Neruda. <b>Gabriela fue la primera latinoamericana en ganarlo.</b>',
   vsEn:'Gabriela Mistral and Pablo Neruda. <b>Gabriela was the first Latin American ever to win it.</b>',
   src:'The Nobel Prize'},
  {reg:13,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'El más alto',rankEn:'The tallest',big:'300m',
   labelEs:'el Sky Costanera: el mirador más alto de Sudamérica',labelEn:'the Sky Costanera: the highest viewpoint in South America',
   vsEs:'300 metros sobre Santiago con vista 360°, <b>la cordillera nevada de fondo</b>. El edificio más alto de la región.',
   vsEn:'300 metres above Santiago with a 360° view, <b>the snowy Andes behind</b>. The tallest building in the region.',
   src:'CTBUH / Sky Costanera'},
  {reg:13,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'El más extenso',rankEn:'The most extensive',big:'149km',
   labelEs:'el Metro de Santiago: la red de metro más extensa de Sudamérica',labelEn:'the Santiago Metro: the most extensive metro network in South America',
   vsEs:'7 líneas, 143 estaciones y de los <b>más modernos de Latinoamérica</b>. Mueve millones cada día.',
   vsEn:'7 lines, 143 stations and one of <b>the most modern in Latin America</b>. It moves millions every day.',
   src:'Metro de Santiago, 2025'},
  {reg:13,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Esquí y ciudad',rankEn:'Ski & city',big:'⛷️',
   labelEs:'centros de esquí de clase mundial a una hora de la capital',labelEn:'world-class ski resorts one hour from the capital',
   vsEs:'Pocas capitales del mundo te dejan <b>esquiar en los Andes y cenar en la ciudad</b> el mismo día.',
   vsEn:'Few world capitals let you <b>ski in the Andes and dine downtown</b> on the same day.',
   src:'Sernatur'},
  {reg:13,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Hub de unicornios',rankEn:'Unicorn hub',big:'🦄',
   labelEs:'Santiago: cuna de startups unicornio que conquistan Latinoamérica',labelEn:'Santiago: home of unicorn startups conquering Latin America',
   vsEs:'De acá salieron <b>Cornershop, NotCo y Betterfly</b>: tecnología chilena valorada en miles de millones.',
   vsEn:'Home of <b>Cornershop, NotCo and Betterfly</b>: Chilean tech valued in the billions.',
   src:'Startup Chile / prensa'},

  /* ---------- O'HIGGINS (6) ---------- */
  {reg:6,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'#1 del mundo',rankEn:'#1 in the world',big:'59%',
   labelEs:'de las cerezas del mundo las exporta Chile',labelEn:"of the world's exported cherries come from Chile",
   vsEs:'Chile es <b>el mayor exportador de cerezas del planeta</b>: más de la mitad del mercado global.',
   vsEn:'Chile is <b>the largest cherry exporter on Earth</b>: more than half the global market.',
   src:'SUBREI, 2025'},
  {reg:6,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Patrimonio',rankEn:'Heritage',big:'⛏️',
   labelEs:'Sewell: la "ciudad de las escaleras" minera, Patrimonio de la Humanidad',labelEn:'Sewell: the mining "city of stairs", a World Heritage Site',
   vsEs:'Una ciudad entera <b>colgada en la cordillera</b> a 2.000 m, construida para la mina de cobre más grande bajo tierra.',
   vsEn:'An entire town <b>clinging to the Andes</b> at 2,000 m, built for the largest underground copper mine.',
   src:'UNESCO'},
  {reg:6,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Mina gigante',rankEn:'Giant mine',big:'El Teniente',
   labelEs:'El Teniente: la mina de cobre subterránea más grande del mundo',labelEn:'El Teniente: the largest underground copper mine in the world',
   vsEs:'Más de <b>3.000 km de túneles</b> bajo la cordillera. Un siglo extrayendo el metal que mueve a Chile.',
   vsEn:'Over <b>3,000 km of tunnels</b> beneath the Andes. A century mining the metal that drives Chile.',
   src:'Codelco'},
  {reg:6,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Tradición huasa',rankEn:'Cowboy tradition',big:'🐎',
   labelEs:'corazón del rodeo y la cultura huasa, deporte nacional de Chile',labelEn:'heart of rodeo and huaso culture, Chile\'s national sport',
   vsEs:'El rodeo es <b>el segundo deporte más practicado del país</b>: pura tradición campesina chilena.',
   vsEn:'Rodeo is <b>the second most practiced sport in the country</b>: pure Chilean rural tradition.',
   src:'Federación del Rodeo Chileno'},
  {reg:6,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Termas y montaña',rankEn:'Hot springs',big:'♨️',
   labelEs:'Termas de Cauquenes: aguas termales usadas desde hace siglos',labelEn:'Cauquenes Hot Springs: thermal waters used for centuries',
   vsEs:'Tan famosas que <b>Charles Darwin las visitó</b> en 1834 durante su viaje por Chile.',
   vsEn:'So renowned that <b>Charles Darwin visited them</b> in 1834 during his journey through Chile.',
   src:'Memoria Chilena'},

  /* ===================== ZONA CENTRO-SUR ===================== */

  /* ---------- MAULE (7) ---------- */
  {reg:7,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Líder del sur',rankEn:'Southern leader',big:'🍷',
   labelEs:'corazón del vino chileno: #1 exportador del hemisferio sur',labelEn:'heart of Chilean wine: #1 exporter in the southern hemisphere',
   vsEs:'Chile es el <b>4º mayor exportador de vino del mundo</b>, solo tras Italia, España y Francia.',
   vsEn:"Chile is the <b>world's 4th largest wine exporter</b>, behind only Italy, Spain and France.",
   src:'SUBREI, 2025'},
  {reg:7,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'El valle más antiguo',rankEn:'The oldest valley',big:'500',
   labelEs:'años de tradición: el Maule es la zona vinícola más antigua de Chile',labelEn:'years of tradition: the Maule is Chile\'s oldest wine region',
   vsEs:'Aquí sobreviven parras de la cepa País <b>cultivadas sin riego por más de un siglo</b>, pura raíz histórica.',
   vsEn:'Here the País grape survives on vines <b>grown without irrigation for over a century</b>, pure historic roots.',
   src:'Valle del Maule / Catadelvino'},
  {reg:7,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Cepa renacida',rankEn:'Reborn grape',big:'Carménère',
   labelEs:'el Carménère: la cepa que el mundo dio por perdida y revive en Chile',labelEn:'Carménère: the grape the world thought extinct, reborn in Chile',
   vsEs:'Desaparecida en Europa por una plaga, <b>sobrevivió escondida en Chile</b> y hoy es la cepa emblema del país.',
   vsEn:'Wiped out in Europe by a plague, it <b>survived hidden in Chile</b> and is now the country\'s flagship grape.',
   src:'Wines of Chile'},
  {reg:7,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Laguna mágica',rankEn:'Magical lagoon',big:'7 tazas',
   labelEs:'las Siete Tazas: pozones turquesa esculpidos en roca volcánica',labelEn:'the Seven Cups: turquoise pools carved into volcanic rock',
   vsEs:'El río Claro cae formando <b>siete piscinas naturales en cascada</b>. Una joya escondida del Maule.',
   vsEn:'The Claro River falls forming <b>seven natural pools in cascade</b>. A hidden gem of the Maule.',
   src:'CONAF'},
  {reg:7,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Tradición campesina',rankEn:'Rural tradition',big:'🎸',
   labelEs:'cuna de la tonada y el folclor campesino chileno',labelEn:'cradle of the tonada and Chilean rural folk music',
   vsEs:'El campo maulino guarda <b>las raíces más profundas de la música tradicional</b> de Chile.',
   vsEn:'The Maule countryside holds <b>the deepest roots of Chile\'s traditional music</b>.',
   src:'Memoria Chilena'},

  /* ---------- ÑUBLE (16) ---------- */
  {reg:16,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cuna de genios',rankEn:'Cradle of greats',big:'🎹',
   labelEs:'Chillán: tierra de Claudio Arrau, uno de los mayores pianistas de la historia',labelEn:"Chillán: home of Claudio Arrau, one of history's greatest pianists",
   vsEs:'Arrau es considerado <b>uno de los mejores intérpretes de piano del siglo XX</b> a nivel mundial.',
   vsEn:'Arrau is regarded as <b>one of the greatest piano performers of the 20th century</b> worldwide.',
   src:'Memoria Chilena'},
  {reg:16,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cuna de un prócer',rankEn:'Cradle of a hero',big:'🇨🇱',
   labelEs:'Chillán: cuna de Bernardo O\'Higgins, padre de la patria',labelEn:'Chillán: birthplace of Bernardo O\'Higgins, founding father of Chile',
   vsEs:'El líder que <b>firmó la independencia de Chile</b> nació en esta tierra del valle central.',
   vsEn:'The leader who <b>signed Chile\'s independence</b> was born in this central-valley land.',
   src:'Memoria Chilena'},
  {reg:16,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Nieve y termas',rankEn:'Snow & springs',big:'♨️',
   labelEs:'Nevados de Chillán: esquí y termas naturales al pie de un volcán',labelEn:'Nevados de Chillán: skiing and natural hot springs at the foot of a volcano',
   vsEs:'Uno de los pocos lugares donde <b>esquías de día y te bañas en aguas termales</b> volcánicas al atardecer.',
   vsEn:'One of the few places where you <b>ski by day and soak in volcanic hot springs</b> at dusk.',
   src:'Sernatur'},
  {reg:16,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Arte mural',rankEn:'Mural art',big:'🎨',
   labelEs:'Chillán: murales de Siqueiros y Guerrero, regalo de México tras el terremoto',labelEn:'Chillán: murals by Siqueiros and Guerrero, a gift from Mexico after the earthquake',
   vsEs:'Tras el terremoto de 1939, México regaló una escuela con <b>murales de maestros mundiales</b>.',
   vsEn:'After the 1939 earthquake, Mexico gifted a school with <b>murals by world-class masters</b>.',
   src:'Memoria Chilena'},
  {reg:16,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Sabor con sello',rankEn:'Flavor with seal',big:'🍖',
   labelEs:'la longaniza de Chillán: tradición con denominación de origen',labelEn:'the Chillán longaniza sausage: tradition with protected origin',
   vsEs:'Un producto tan identitario que tiene <b>sello de origen propio</b>: pura cultura gastronómica chilena.',
   vsEn:'A product so iconic it has its <b>own origin label</b>: pure Chilean food culture.',
   src:'INAPI'},

  /* ---------- BIOBÍO (8) ---------- */
  {reg:8,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cuna del rock',rankEn:'Rock cradle',big:'🎸',
   labelEs:'Concepción: la ciudad que parió el rock chileno moderno',labelEn:'Concepción: the city that birthed modern Chilean rock',
   vsEs:'De acá salieron Los Tres, Emociones Clandestinas y una <b>escena musical que marcó al país</b>.',
   vsEn:'Home of Los Tres and a <b>music scene that shaped the whole country</b>.',
   src:'Memoria Chilena'},
  {reg:8,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Cascada icónica',rankEn:'Iconic waterfall',big:'💦',
   labelEs:'el Salto del Laja: una de las cascadas más famosas de Chile',labelEn:'the Salto del Laja: one of Chile\'s most famous waterfalls',
   vsEs:'Considerado <b>"la entrada al sur de Chile"</b>: el río Laja cae en una cortina de agua espectacular.',
   vsEn:'Known as <b>"the gateway to southern Chile"</b>: the Laja River drops in a spectacular curtain of water.',
   src:'Sernatur'},
  {reg:8,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Polo universitario',rankEn:'University hub',big:'🎓',
   labelEs:'Concepción: una de las grandes capitales universitarias de Chile',labelEn:'Concepción: one of Chile\'s great university capitals',
   vsEs:'Su universidad y su Barrio Universitario hacen de "Conce" <b>un motor de ciencia y talento joven</b>.',
   vsEn:'Its university and student quarter make "Conce" <b>an engine of science and young talent</b>.',
   src:'Universidad de Concepción'},
  {reg:8,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Ombligo de Chile',rankEn:'Navel of Chile',big:'📍',
   labelEs:'aquí está el centro geográfico histórico del país',labelEn:'here lies the country\'s historic geographic center',
   vsEs:'Cerca de Concepción está <b>"el ombligo de Chile"</b>: el punto medio de este país imposible y angosto.',
   vsEn:'Near Concepción lies <b>"the navel of Chile"</b>: the midpoint of this impossibly narrow country.',
   src:'Memoria Chilena'},
  {reg:8,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Río bravo',rankEn:'Wild river',big:'380km',
   labelEs:'el río Biobío: uno de los más caudalosos y emblemáticos de Chile',labelEn:'the Biobío River: one of Chile\'s mightiest and most emblematic rivers',
   vsEs:'Frontera histórica del pueblo mapuche y <b>meca mundial del rafting</b> por sus rápidos.',
   vsEn:'Historic frontier of the Mapuche people and a <b>world rafting mecca</b> for its rapids.',
   src:'Sernatur'},

  /* ---------- LA ARAUCANÍA (9) ---------- */
  {reg:9,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Pueblo vivo',rankEn:'Living people',big:'Mapuche',
   labelEs:'la cultura mapuche resistió siglos y sigue viva',labelEn:'the Mapuche culture resisted for centuries and is still alive',
   vsEs:'<b>Nunca conquistados por los incas</b>; resistieron a la corona española por más de 300 años.',
   vsEn:'<b>Never conquered by the Incas</b>; they resisted the Spanish crown for over 300 years.',
   src:'Memoria Chilena'},
  {reg:9,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Árbol sagrado',rankEn:'Sacred tree',big:'1.000+',
   labelEs:'la araucaria: árbol endémico que vive más de mil años',labelEn:'the araucaria: an endemic tree that lives over a thousand years',
   vsEs:'Solo crece aquí y en Argentina. La "Araucaria Madre" tiene <b>más de 1.000 años</b>: sagrada para los mapuche.',
   vsEn:'It grows only here and in Argentina. The "Mother Araucaria" is <b>over 1,000 years old</b>: sacred to the Mapuche.',
   src:'Wikipedia / CONAF'},
  {reg:9,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Reserva UNESCO',rankEn:'UNESCO reserve',big:'🌋',
   labelEs:'Conguillío y los volcanes: una Reserva de la Biosfera protegida por la UNESCO',labelEn:'Conguillío and the volcanoes: a UNESCO-protected Biosphere Reserve',
   vsEs:'Volcanes activos, lagos y bosques de araucarias en <b>más de un millón de hectáreas protegidas</b>.',
   vsEn:'Active volcanoes, lakes and araucaria forests across <b>over a million protected hectares</b>.',
   src:'UNESCO'},
  {reg:9,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Aventura y termas',rankEn:'Adventure & springs',big:'🌋',
   labelEs:'Pucón y el volcán Villarrica: capital de aventura del sur',labelEn:'Pucón and the Villarrica volcano: the south\'s adventure capital',
   vsEs:'Subir un <b>volcán activo</b>, bajar en rafting y terminar en termas el mismo día. Destino mundial.',
   vsEn:'Climb an <b>active volcano</b>, raft down rapids and end in hot springs the same day. A world destination.',
   src:'Sernatur'},
  {reg:9,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Lengua viva',rankEn:'Living language',big:'Mapudungun',
   labelEs:'el mapudungun: la lengua mapuche que sigue hablándose hoy',labelEn:'Mapudungun: the Mapuche language still spoken today',
   vsEs:'Palabras como "poncho", "guata" y "pichintún" <b>vienen de esta lengua viva</b>. Identidad pura.',
   vsEn:'Words used across Chile every day <b>come from this living language</b>. Pure identity.',
   src:'Memoria Chilena'},

  /* ===================== ZONA SUR-AUSTRAL ===================== */

  /* ---------- LOS RÍOS (14) ---------- */
  {reg:14,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Casi milenario',rankEn:'Nearly ancient',big:'~5.000',
   labelEs:'años podría tener el Gran Abuelo, uno de los árboles más viejos del mundo',labelEn:'years: the Gran Abuelo may be one of the oldest trees on Earth',
   vsEs:'Un alerce en el sur de Chile que <b>podría ser el árbol vivo más antiguo del planeta</b> (estudio en revisión).',
   vsEn:'An alerce in southern Chile that <b>may be the oldest living tree on the planet</b> (study under review).',
   src:'Science, 2022'},
  {reg:14,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Capital cervecera',rankEn:'Beer capital',big:'🍺',
   labelEs:'Valdivia: la capital de la cerveza artesanal de Chile',labelEn:'Valdivia: Chile\'s craft beer capital',
   vsEs:'Herencia alemana y aguas puras hacen de Valdivia <b>la cuna cervecera del país</b>, con su festival propio.',
   vsEn:'German heritage and pure waters make Valdivia <b>the country\'s brewing cradle</b>, with its own festival.',
   src:'Black Beer Festival / Kunstmann'},
  {reg:14,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Ciudad-río',rankEn:'River city',big:'🦭',
   labelEs:'Valdivia: la ciudad de los ríos, con lobos marinos en pleno centro',labelEn:'Valdivia: the city of rivers, with sea lions in the heart of town',
   vsEs:'En el mercado fluvial <b>los lobos marinos esperan junto a los pescadores</b>. Una postal única en Chile.',
   vsEn:'At the river market, <b>sea lions wait beside the fishermen</b>. A scene unique in Chile.',
   src:'Sernatur'},
  {reg:14,cat:'cielo',catEs:'Cielo y ciencia',catEn:'Sky & science',rankEs:'Polo científico',rankEn:'Science hub',big:'🔬',
   labelEs:'Valdivia: una de las grandes capitales científicas del sur de Chile',labelEn:'Valdivia: one of the great science capitals of southern Chile',
   vsEs:'Su universidad austral es <b>referente en ciencia y bosques nativos</b>, atrayendo investigadores del mundo.',
   vsEn:'Its southern university is a <b>leader in science and native forests</b>, drawing researchers worldwide.',
   src:'Universidad Austral de Chile'},
  {reg:14,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Selva fría',rankEn:'Cold rainforest',big:'🌧️',
   labelEs:'la selva valdiviana: uno de los pocos bosques templados lluviosos del mundo',labelEn:'the Valdivian rainforest: one of the few temperate rainforests on Earth',
   vsEs:'Un ecosistema <b>tan raro que solo existe en un puñado de lugares del planeta</b>. Verde infinito.',
   vsEn:'An ecosystem <b>so rare it exists in only a handful of places on Earth</b>. Endless green.',
   src:'WWF'},

  /* ---------- LOS LAGOS (10) ---------- */
  {reg:10,cat:'recursos',catEs:'Recursos',catEn:'Resources',rankEs:'Top 2 mundial',rankEn:'World top 2',big:'31%',
   labelEs:'del salmón del mundo lo exporta Chile, segundo productor global',labelEn:"of the world's exported salmon comes from Chile, the 2nd biggest producer",
   vsEs:'Las aguas frías del sur hacen de Chile <b>una potencia mundial del salmón</b>.',
   vsEn:'The cold southern waters make Chile <b>a global salmon powerhouse</b>.',
   src:'SUBREI, 2025'},
  {reg:10,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Patrimonio',rankEn:'Heritage',big:'⛪',
   labelEs:'las iglesias de Chiloé: madera pura, Patrimonio de la Humanidad',labelEn:'the churches of Chiloé: pure wood, World Heritage Sites',
   vsEs:'Construidas <b>sin un solo clavo</b>, una tradición única de carpintería que la UNESCO protege.',
   vsEn:'Built <b>without a single nail</b>, a unique carpentry tradition protected by UNESCO.',
   src:'UNESCO'},
  {reg:10,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Cocina ancestral',rankEn:'Ancestral cuisine',big:'🦪',
   labelEs:'el curanto: comida cocida bajo tierra con piedras calientes, tradición de Chiloé',labelEn:'the curanto: food cooked underground with hot stones, a Chiloé tradition',
   vsEs:'Una forma de cocinar <b>de siglos de antigüedad</b>, mariscos y carnes bajo la tierra. Pura identidad.',
   vsEn:'A centuries-old way of cooking <b>seafood and meat under the earth</b>. Pure identity.',
   src:'Memoria Chilena'},
  {reg:10,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Casas sobre el agua',rankEn:'Houses on water',big:'🏘️',
   labelEs:'los palafitos de Chiloé: coloridas casas sobre pilotes en el mar',labelEn:'the palafitos of Chiloé: colorful houses on stilts over the sea',
   vsEs:'Casas de madera <b>suspendidas sobre el agua</b>, una de las postales más icónicas del sur de Chile.',
   vsEn:'Wooden houses <b>suspended over the water</b>, one of the most iconic images of southern Chile.',
   src:'Sernatur'},
  {reg:10,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Volcán perfecto',rankEn:'Perfect volcano',big:'🌋',
   labelEs:'el volcán Osorno: un cono casi perfecto sobre el lago Llanquihue',labelEn:'the Osorno volcano: an almost perfect cone above Lake Llanquihue',
   vsEs:'Comparado con el monte Fuji por su forma, se alza sobre <b>el segundo lago más grande de Chile</b>.',
   vsEn:'Compared to Mt. Fuji for its shape, it rises over <b>Chile\'s second-largest lake</b>.',
   src:'Sernatur'},

  /* ---------- AYSÉN (11) ---------- */
  {reg:11,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Agua más pura',rankEn:'Purest water',big:'💧',
   labelEs:'la Patagonia de Aysén tiene algunas de las aguas más puras del mundo',labelEn:'Patagonian Aysén holds some of the purest waters in the world',
   vsEs:'El río Baker y la Carretera Austral: <b>naturaleza casi intacta</b> que casi no existe ya en el planeta.',
   vsEn:'The Baker River and the Carretera Austral: <b>nearly untouched nature</b> that barely exists anymore.',
   src:'Conaf / National Geographic'},
  {reg:11,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Maravilla de mármol',rankEn:'Marble wonder',big:'💎',
   labelEs:'las Capillas de Mármol: cuevas esculpidas por el agua sobre un lago turquesa',labelEn:'the Marble Caves: caverns carved by water over a turquoise lake',
   vsEs:'En el lago General Carrera, <b>el más grande de Chile</b>: mármol pulido por milenios de agua glaciar.',
   vsEn:'On Lake General Carrera, <b>Chile\'s largest</b>: marble polished by millennia of glacial water.',
   src:'Sernatur'},
  {reg:11,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Reserva mundial',rankEn:'World reserve',big:'#3',
   labelEs:'los Campos de Hielo: la tercera reserva de agua dulce más grande del mundo',labelEn:'the Ice Fields: the third-largest freshwater reserve on Earth',
   vsEs:'Solo superados por la <b>Antártica y Groenlandia</b>. Un manto de hielo de 370 km de largo.',
   vsEn:'Surpassed only by <b>Antarctica and Greenland</b>. An ice sheet 370 km long.',
   src:'Ruta de los Parques'},
  {reg:11,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Ruta mítica',rankEn:'Mythic road',big:'🛣️',
   labelEs:'la Carretera Austral: una de las rutas escénicas más bellas del planeta',labelEn:'the Carretera Austral: one of the most scenic roads on the planet',
   vsEs:'1.240 km entre fiordos, glaciares y bosques. <b>Un viaje de aventura de nivel mundial.</b>',
   vsEn:'1,240 km through fjords, glaciers and forests. <b>A world-class adventure journey.</b>',
   src:'Sernatur'},
  {reg:11,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Pueblo de pasarelas',rankEn:'Boardwalk town',big:'🪵',
   labelEs:'Caleta Tortel: un pueblo sin calles, conectado solo por pasarelas de madera',labelEn:'Caleta Tortel: a town with no streets, linked only by wooden walkways',
   vsEs:'No hay autos: <b>se camina sobre pasarelas de ciprés</b> entre los fiordos. Único en Chile.',
   vsEn:'No cars: <b>you walk on cypress boardwalks</b> between the fjords. Unique in Chile.',
   src:'Sernatur'},

  /* ---------- MAGALLANES (12) ---------- */
  {reg:12,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'8ª maravilla',rankEn:'8th wonder',big:'🏔️',
   labelEs:'Torres del Paine: elegida la octava maravilla del mundo',labelEn:'Torres del Paine: voted the eighth wonder of the world',
   vsEs:'En 2013 ganó con <b>más de 5 millones de votos</b>. National Geographic la puso entre los lugares más bellos.',
   vsEn:'In 2013 it won with <b>over 5 million votes</b>. National Geographic ranked it among the most beautiful places.',
   src:'Virtual Tourist / Nat Geo'},
  {reg:12,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'La más austral',rankEn:'Southernmost',big:'🌎',
   labelEs:'Cabo de Hornos: la reserva de la biosfera más austral del mundo',labelEn:'Cape Horn: the southernmost biosphere reserve in the world',
   vsEs:'El último pedazo de tierra antes de la Antártica. <b>El fin del mundo, literalmente.</b>',
   vsEn:'The last piece of land before Antarctica. <b>The end of the world, literally.</b>',
   src:'UNESCO'},
  {reg:12,cat:'natura',catEs:'Naturaleza',catEn:'Nature',rankEs:'Colonias enormes',rankEn:'Huge colonies',big:'🐧',
   labelEs:'pingüineras gigantes: miles de pingüinos en Isla Magdalena y seno Otway',labelEn:'giant penguin colonies: thousands of penguins on Magdalena Island and Otway Sound',
   vsEs:'Caminar entre <b>miles de pingüinos de Magallanes</b> en su hábitat natural. Espectáculo de la fauna austral.',
   vsEn:'Walk among <b>thousands of Magellanic penguins</b> in their natural habitat. A wildlife spectacle.',
   src:'CONAF'},
  {reg:12,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Ruta histórica',rankEn:'Historic route',big:'⛵',
   labelEs:'el Estrecho de Magallanes: el paso que conectó al mundo por primera vez',labelEn:'the Strait of Magellan: the passage that first connected the world',
   vsEs:'Por aquí pasó <b>la primera vuelta al mundo</b> en 1520. Un hito de la historia de la humanidad.',
   vsEn:'The <b>first voyage around the world</b> passed through here in 1520. A milestone of human history.',
   src:'Memoria Chilena'},
  {reg:12,cat:'gente',catEs:'Gente y cultura',catEn:'People & culture',rankEs:'Puerta a la Antártica',rankEn:'Gateway to Antarctica',big:'🧊',
   labelEs:'Punta Arenas: una de las principales puertas de entrada a la Antártica',labelEn:'Punta Arenas: a main gateway to Antarctica',
   vsEs:'Desde acá parten expediciones científicas de todo el mundo al <b>continente blanco</b>.',
   vsEn:'Scientific expeditions from around the world depart here to the <b>white continent</b>.',
   src:'INACH'}

];
